fastlane_version "2.39.1"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|

    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'CheckFuelPrice', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : [ENV[NOTIFY_EMAIL_ADDRESS]] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    ##
    build_time = Time.new.strftime("%Y.%m.%d %H:%M")
    notes = 'Hockey build at ' + build_time

    hockey( api_token: ENV['FL_HOCKEY_API_TOKEN'], notes: notes)
    
    #crashlytics(api_token: ENV['CRASHLYTICS_API_TOKEN'],
    #         build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
    #               emails: emails,
    #               groups: groups,
    #                notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
    #        notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
